# Generated by Django 5.2.6 on 2025-09-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='winner_amount',
            new_name='winning_amount',
        ),
        migrations.AddField(
            model_name='matches',
            name='player1_disconnected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matches',
            name='player2_disconnected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matches',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('full', 'Full'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
        migrations.DeleteModel(
            name='MatchMaking',
        ),
    ]
