# Generated by Django 5.2.6 on 2025-09-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0004_alter_matches_player1_alter_matches_player2_and_more'),
        ('Player', '0005_alter_player_aadhar_no_alter_player_avatar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player2', to='Player.player'),
        ),
    ]
