# Generated by Django 5.2.6 on 2025-09-17 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(default=1, max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.player'),
        ),
    ]
