# Generated by Django 5.2.6 on 2025-09-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0002_player_player_id_alter_bankdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='coin',
            field=models.IntegerField(default=0),
        ),
    ]
