# Generated by Django 5.2.6 on 2025-09-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0003_alter_player_bonus_alter_player_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
