# Generated by Django 5.2.6 on 2025-09-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0004_alter_player_avatar_no_alter_player_pan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
