# Generated by Django 5.2.6 on 2025-09-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0005_alter_player_aadhar_no_alter_player_avatar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cashback',
            field=models.FloatField(default=0.0),
        ),
    ]
