# Generated by Django 5.2.6 on 2025-09-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0006_player_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='aadhar_verified',
            field=models.BooleanField(default=False),
        ),
    ]
