# Generated by Django 5.2.6 on 2025-09-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0007_player_aadhar_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='player',
            name='aadhar_verified',
        ),
    ]
