from django.urls import path
from .views import *

urlpatterns = [
    path('login/', admin_login, name='admin_login'),
    path('logout/', admin_logout, name='admin_logout'),
    path('', dashboard_view, name='dashboard'),
    path('dashboard-data', dashboard_data, name='dashboard_data'),
    path('player', player_view, name='player'),
    path('player-data', player_data, name='player_data'),
    path('player-data/block-<int:player_id>', block_player, name='block_player'),
    path('player-data/delete-<int:player_id>', delete_player, name='delete_player'),
    path('games', games_view, name='games'),
    path('games-data', games_data, name='games_data'),
    path('add-game', add_game, name='add_game'),
    path('edit-game/<int:id>/', edit_game, name='edit_game'),
    path('delete-game/<int:id>', delete_game, name='delete_game'),
    path('block-game/<int:id>', block_game, name='block_game'),
    path('matches-completed', matches_comp_view, name='matches_completed'),
    path('matches-completed-data', matches_comp_data, name='matches_completed_data'),
    path('matches-ongoing', matches_ong_view, name='matches_ongoing'),
    path('matches-ongoing-data', matches_ong_data, name='matches_ongoing_data'),
    path('matches-bonus', bonus_games_view, name='matches_bonus'),
    path('matches-bonus-data', bonus_games_data, name='matches_bonus_data'),
    path('commission', commission_view, name='commission'),
    path('commission-data', commission_data, name='commission_data'),
    path('credit-transfers', credit_trans_view, name='credit_transfers'),
    path('credit-transfer-data', credit_trans_data, name='credit_transfer_data'),
    path('debit-transfers', debit_trans_view, name='debit_transfers'),
    path('debit-transfer-data', debit_trans_data, name='debit_transfer_data'),
    path('app-settings', app_settings_view, name='app_settings'),
    path('add-settings', add_setting, name='add_settings'),
    path('edit-settings', edit_setting, name='edit_settings'),
    path('web-games', web_games_view, name='web_games'),
    path('web-games-data', web_games_data, name='web_games_data'),
    path('add-web-games', add_web_games, name='add_web_games'),
    path('edit-web-games/<int:id>/', edit_web_games, name='edit_web_games'),
    path('delete-web-games/<int:id>/', delete_web_games, name='delete_web_games'),
    path('block-web-games/<int:id>/', block_web_game, name='block_web_game'),
    path('web-contact', web_contact_view, name='web_contact'),
    path('web-contact-data', web_contact_data, name='web_contact_data'),
]