# Generated by Django 5.2.6 on 2025-09-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, null=True)),
                ('gst_percentage', models.FloatField(default=0.0)),
                ('withdrawal_limit', models.IntegerField(default=0)),
                ('daily_withdraw_count', models.IntegerField(default=0)),
            ],
        ),
    ]
